# MARF documentation makefile
# Use with GNU make
#
# Copyright (c) 2003 - 2006 The MARF Research and Development Group
#
# $Header: /cvsroot/marf/marf/doc/src/Makefile,v 1.7 2006/01/15 20:51:55 mokhov Exp $

all distro clean maintainer-clean:
	make -C tex $@

# EOF
